### ISSUE TITLE
Auto-generate nav

### ISSUE THREAD

**Issue by Andre601** [xenondevs/Docs#2]
Looking at the `mkdocs.yml` file, I can see that the Nova docs would require people to add extra pages to it for stuff such as adding translations.

It could therefore be beneficial to use the [Awesome Pages plugin](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/) to auto-generate the navigation. The plugin does to my knowledge work with the i18n plugin currently used by you.
And while we're on the topic of i18n. Maybe consider using a [folder structure](https://github.com/ultrabug/mkdocs-static-i18n#folder-based-docs-structure) rather than the default suffix-based structure to allow a more clean result structure of the files.

Those are just suggestions and don't need to be looked into if not needed.

**Comment by ByteZ1337** [comment]
We tried using the i18n folder structure. It kept failing to build the website for some reason, even though we had the exact config as the example. We'll look into auto generating the navigation.
